from pyspark import SparkConf
from pyspark.sql import SparkSession

def create_spark_session():
    conf = SparkConf()
    conf.set('spark.app.name', 'Create Base Table')

    spark = SparkSession.builder\
            .config(conf = conf)\
            .getOrCreate()
    
    return spark

def create_base_table():
    spark = create_spark_session()

    wide_table = spark.read.format('bigquery')\
                .load('data-engineering-478006.spark_dataset.wide_table')

    clean_wide_table = wide_table.dropDuplicates(subset = ['BASE_YMD', 'RTE_ID', 'STOP_ID', 'STOP_SEQ'])
    clean_wide_table.createOrReplaceTempView('clean_wide_table')
    clean_wide_table.cache()
    clean_wide_table.count()

    temp = spark.sql("""
        WITH route_daily_total AS (
            SELECT BASE_YMD, RTE_ID, MAX(TOTAL_ON) AS TOTAL_ON, MAX(TOTAL_OFF) AS TOTAL_OFF
            FROM clean_wide_table
            GROUP BY 1, 2
        ), avg_daily_total AS (
            SELECT BASE_YMD, RTE_ID,
                AVG(TOTAL_ON) OVER(PARTITION BY RTE_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_TOTAL_ON,
                AVG(TOTAL_OFF) OVER(PARTITION BY RTE_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_TOTAL_OFF
            FROM route_daily_total
        )
        SELECT c.BASE_YMD, c.YEAR, c.MONTH, c.DAY, DAY_OF_WEEK, IS_WEEKEND, c.RTE_ID,
            CASE WHEN RTE_TYPE = '' THEN '심야' ELSE RTE_TYPE END AS RTE_TYPE,
            DIST, RTE_STOP_COUNT, STOP_ID, DONG_ID, SGG_NM, RTE_SGG_COUNT, RTE_DONG_COUNT, STOP_TYPE, LAT, LOT,
            STOP_SEQ, LNKG_LEN, GTON_TNOPE, GTOFF_TNOPE,
            AVG(GTON_TNOPE) OVER(PARTITION BY c.RTE_ID, STOP_ID ORDER BY c.BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_STOP_ON,
            AVG(GTOFF_TNOPE) OVER(PARTITION BY c.RTE_ID, STOP_ID ORDER BY c.BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_STOP_OFF,
            BUS_OPR, BUS_OPR_00, BUS_O  PR_01, BUS_OPR_02, BUS_OPR_03, BUS_OPR_04, BUS_OPR_05, BUS_OPR_06, BUS_OPR_07,
            BUS_OPR_08, BUS_OPR_09, BUS_OPR_10, BUS_OPR_11, BUS_OPR_12, BUS_OPR_13, BUS_OPR_14, BUS_OPR_15,
            BUS_OPR_16, BUS_OPR_17, BUS_OPR_18, BUS_OPR_19, BUS_OPR_20, BUS_OPR_21, BUS_OPR_22, BUS_OPR_23,
            AVG(BUS_OPR) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_IMP,
            AVG(BUS_OPR_00) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_00_IMP,
            AVG(BUS_OPR_01) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_01_IMP,
            AVG(BUS_OPR_02) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_02_IMP,
            AVG(BUS_OPR_03) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_03_IMP,
            AVG(BUS_OPR_04) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_04_IMP,
            AVG(BUS_OPR_05) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_05_IMP,
            AVG(BUS_OPR_06) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_06_IMP,
            AVG(BUS_OPR_07) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_07_IMP,
            AVG(BUS_OPR_08) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_08_IMP,
            AVG(BUS_OPR_09) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_09_IMP,
            AVG(BUS_OPR_10) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_10_IMP,
            AVG(BUS_OPR_11) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_11_IMP,
            AVG(BUS_OPR_12) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_12_IMP,
            AVG(BUS_OPR_13) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_13_IMP,
            AVG(BUS_OPR_14) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_14_IMP,
            AVG(BUS_OPR_15) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_15_IMP,
            AVG(BUS_OPR_16) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_16_IMP,
            AVG(BUS_OPR_17) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_17_IMP,
            AVG(BUS_OPR_18) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_18_IMP,
            AVG(BUS_OPR_19) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_19_IMP,
            AVG(BUS_OPR_20) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_20_IMP,
            AVG(BUS_OPR_21) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_21_IMP,
            AVG(BUS_OPR_22) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_22_IMP,
            AVG(BUS_OPR_23) OVER(PARTITION BY c.RTE_ID, STOP_ID) AS BUS_OPR_23_IMP,
            t.AVG_7DAY_TOTAL_ON, t.AVG_7DAY_TOTAL_OFF,
            BUS_PSNG, BUS_PSNG_00, BUS_PSNG_01, BUS_PSNG_02, BUS_PSNG_03, BUS_PSNG_04, BUS_PSNG_05, BUS_PSNG_06, BUS_PSNG_07,
            BUS_PSNG_08, BUS_PSNG_09, BUS_PSNG_10, BUS_PSNG_11, BUS_PSNG_12, BUS_PSNG_13, BUS_PSNG_14, BUS_PSNG_15,
            BUS_PSNG_16, BUS_PSNG_17, BUS_PSNG_18, BUS_PSNG_19, BUS_PSNG_20, BUS_PSNG_21, BUS_PSNG_22, BUS_PSNG_23
        FROM clean_wide_table c
        JOIN avg_daily_total t
        ON c.BASE_YMD = t.BASE_YMD AND c.RTE_ID = t.RTE_ID
    """)
    temp.createOrReplaceTempView('temp')

    temp2 = spark.sql("""
        SELECT
            BASE_YMD, YEAR, MONTH, DAY, DAY_OF_WEEK, IS_WEEKEND, RTE_ID, RTE_TYPE, DIST, RTE_STOP_COUNT,
            STOP_ID, DONG_ID, SGG_NM, RTE_SGG_COUNT, RTE_DONG_COUNT, STOP_TYPE, LAT, LOT, STOP_SEQ,
            LNKG_LEN, AVG_7DAY_STOP_ON, AVG_7DAY_STOP_OFF,
            COALESCE(BUS_OPR, BUS_OPR_IMP) AS BUS_OPR,
            COALESCE(BUS_OPR_00, BUS_OPR_00_IMP) AS BUS_OPR_00,
            COALESCE(BUS_OPR_01, BUS_OPR_01_IMP) AS BUS_OPR_01,
            COALESCE(BUS_OPR_02, BUS_OPR_02_IMP) AS BUS_OPR_02,
            COALESCE(BUS_OPR_03, BUS_OPR_03_IMP) AS BUS_OPR_03,
            COALESCE(BUS_OPR_04, BUS_OPR_04_IMP) AS BUS_OPR_04,
            COALESCE(BUS_OPR_05, BUS_OPR_05_IMP) AS BUS_OPR_05,
            COALESCE(BUS_OPR_06, BUS_OPR_06_IMP) AS BUS_OPR_06,
            COALESCE(BUS_OPR_07, BUS_OPR_07_IMP) AS BUS_OPR_07,
            COALESCE(BUS_OPR_08, BUS_OPR_08_IMP) AS BUS_OPR_08,
            COALESCE(BUS_OPR_09, BUS_OPR_09_IMP) AS BUS_OPR_09,
            COALESCE(BUS_OPR_10, BUS_OPR_10_IMP) AS BUS_OPR_10,
            COALESCE(BUS_OPR_11, BUS_OPR_11_IMP) AS BUS_OPR_11,
            COALESCE(BUS_OPR_12, BUS_OPR_12_IMP) AS BUS_OPR_12,
            COALESCE(BUS_OPR_13, BUS_OPR_13_IMP) AS BUS_OPR_13,
            COALESCE(BUS_OPR_14, BUS_OPR_14_IMP) AS BUS_OPR_14,
            COALESCE(BUS_OPR_15, BUS_OPR_15_IMP) AS BUS_OPR_15,
            COALESCE(BUS_OPR_16, BUS_OPR_16_IMP) AS BUS_OPR_16,
            COALESCE(BUS_OPR_17, BUS_OPR_17_IMP) AS BUS_OPR_17,
            COALESCE(BUS_OPR_18, BUS_OPR_18_IMP) AS BUS_OPR_18,
            COALESCE(BUS_OPR_19, BUS_OPR_19_IMP) AS BUS_OPR_19,
            COALESCE(BUS_OPR_20, BUS_OPR_20_IMP) AS BUS_OPR_20,
            COALESCE(BUS_OPR_21, BUS_OPR_21_IMP) AS BUS_OPR_21,
            COALESCE(BUS_OPR_22, BUS_OPR_22_IMP) AS BUS_OPR_22,
            COALESCE(BUS_OPR_23, BUS_OPR_23_IMP) AS BUS_OPR_23,
            AVG_7DAY_TOTAL_ON, AVG_7DAY_TOTAL_OFF, BUS_PSNG,
            BUS_PSNG_00, BUS_PSNG_01, BUS_PSNG_02, BUS_PSNG_03, BUS_PSNG_04, BUS_PSNG_05, BUS_PSNG_06, BUS_PSNG_07,
            BUS_PSNG_08, BUS_PSNG_09, BUS_PSNG_10, BUS_PSNG_11, BUS_PSNG_12, BUS_PSNG_13, BUS_PSNG_14, BUS_PSNG_15,
            BUS_PSNG_16, BUS_PSNG_17, BUS_PSNG_18, BUS_PSNG_19, BUS_PSNG_20, BUS_PSNG_21, BUS_PSNG_22, BUS_PSNG_23,
            GTON_TNOPE, GTOFF_TNOPE
        FROM temp
    """)
    temp2.createOrReplaceTempView('temp2')

    base_table = spark.sql("""
        SELECT
            BASE_YMD, YEAR, MONTH, DAY, DAY_OF_WEEK, IS_WEEKEND, RTE_ID, RTE_TYPE, DIST, RTE_STOP_COUNT,
            STOP_ID, DONG_ID, SGG_NM, RTE_SGG_COUNT, RTE_DONG_COUNT, STOP_TYPE, LAT, LOT, STOP_SEQ,
            LNKG_LEN, AVG_7DAY_STOP_ON, AVG_7DAY_STOP_OFF,
            AVG_7DAY_TOTAL_ON, AVG_7DAY_TOTAL_OFF, BUS_PSNG,
            BUS_PSNG_00, BUS_PSNG_01, BUS_PSNG_02, BUS_PSNG_03, BUS_PSNG_04, BUS_PSNG_05, BUS_PSNG_06, BUS_PSNG_07,
            BUS_PSNG_08, BUS_PSNG_09, BUS_PSNG_10, BUS_PSNG_11, BUS_PSNG_12, BUS_PSNG_13, BUS_PSNG_14, BUS_PSNG_15,
            BUS_PSNG_16, BUS_PSNG_17, BUS_PSNG_18, BUS_PSNG_19, BUS_PSNG_20, BUS_PSNG_21, BUS_PSNG_22, BUS_PSNG_23,
            AVG(BUS_OPR) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR,
            AVG(BUS_OPR_00) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_00,
            AVG(BUS_OPR_01) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_01,
            AVG(BUS_OPR_02) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_02,
            AVG(BUS_OPR_03) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_03,
            AVG(BUS_OPR_04) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_04,
            AVG(BUS_OPR_05) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_05,
            AVG(BUS_OPR_06) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_06,
            AVG(BUS_OPR_07) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_07,
            AVG(BUS_OPR_08) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_08,
            AVG(BUS_OPR_09) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_09,
            AVG(BUS_OPR_10) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_10,
            AVG(BUS_OPR_11) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_11,
            AVG(BUS_OPR_12) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_12,
            AVG(BUS_OPR_13) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_13,
            AVG(BUS_OPR_14) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_14,
            AVG(BUS_OPR_15) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_15,
            AVG(BUS_OPR_16) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_16,
            AVG(BUS_OPR_17) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_17,
            AVG(BUS_OPR_18) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_18,
            AVG(BUS_OPR_19) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_19,
            AVG(BUS_OPR_20) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_20,
            AVG(BUS_OPR_21) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_21,
            AVG(BUS_OPR_22) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_22,
            AVG(BUS_OPR_23) OVER(PARTITION BY RTE_ID, STOP_ID ORDER BY BASE_YMD ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) AS AVG_7DAY_BUS_OPR_23,
            CASE
                WHEN BUS_OPR = 0 THEN 0
                ELSE
                    CASE
                        WHEN (GTON_TNOPE + GTOFF_TNOPE) / BUS_OPR < 2 THEN 1
                        WHEN (GTON_TNOPE + GTOFF_TNOPE) / BUS_OPR < 8 THEN 2
                        ELSE 3
                    END
            END AS TARGET
        FROM temp2
    """)
    base_table = base_table.filter('BASE_YMD > "20260221"').dropna(subset = ['AVG_7DAY_BUS_OPR'])
    base_table.write\
            .format('bigquery')\
            .option('temporaryGcsBucket', 'spark-pipeline-bucket')\
            .option('temporaryGcsPath', 'temp')\
            .mode('overwrite')\
            .save('data-engineering-478006.spark_dataset.base_table')

    clean_wide_table.unpersist()
    
    spark.stop()

if __name__ == '__main__':
    create_base_table()
